# Online Food Delivery Analysis

# Step 1: Data Collection

Load the CSV file

In [2]:
import pandas as pd
from pprint import pprint

In [3]:
# Read the CSV file
df = pd.read_csv("ONINE_FOOD_DELIVERY_ANALYSIS.csv")

In [8]:
# Display the first 5 rows
df.head()

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,NaN,Central,RES936,Restaurant_29,Chinese,10/20/2024,...,NaN,UPI,Delivered,NaN,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,NaN,Female,Chennai,North,RES689,Restaurant_419,Chinese,8/12/2024,...,4849.0,COD,Delivered,NaN,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,NaN,Male,Delhi,NaN,RES723,Restaurant_244,Arabian,12/8/2024,...,737.0,Wallet,Delivered,NaN,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,NaN,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,10/8/2024,...,NaN,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,NaN,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,2/4/2024,...,352.0,Card,Delivered,NaN,DP728,2.0,4.4,Weekend,False,0.12

# Step 2 Data Understanding

In [10]:
# Check the number of rows and columns
print("Dataset Shape:", df.shape)

Dataset Shape: (100000, 25)

In [14]:
# Check column names
print("\n Column Names:")
pprint(df.columns.tolist())

 Column Names:
['Order_ID',
 'Customer_ID',
 'Customer_Age',
 'Customer_Gender',
 'City',
 'Area',
 'Restaurant_ID',
 'Restaurant_Name',
 'Cuisine_Type',
 'Order_Date',
 'Order_Time',
 'Delivery_Time_Min',
 'Distance_km',
 'Order_Value',
 'Discount_Applied',
 'Final_Amount',
 'Payment_Mode',
 'Order_Status',
 'Cancellation_Reason',
 'Delivery_Partner_ID',
 'Delivery_Rating',
 'Restaurant_Rating',
 'Order_Day',
 'Peak_Hour',
 'Profit_Margin']

In [15]:
# Check data types and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Order_ID             100000 non-null  str
 1   Customer_ID          100000 non-null  str
 2   Customer_Age         49907 non-null   float64
 3   Customer_Gender      75144 non-null   str
 4   City                 83274 non-null   str
 5   Area                 83315 non-null   str
 6   Restaurant_ID        100000 non-null  str
 7   Restaurant_Name      100000 non-null  str
 8   Cuisine_Type         83115 non-null   str
 9   Order_Date           98986 non-null   str
 10  Order_Time           98002 non-null   str
 11  Delivery_Time_Min    66641 non-null   float64
 12  Distance_km          66530 non-null   float64
 13  Order_Value          66673 non-null   float64
 14  Discount_Applied     83285 non-null   float64
 15  Final_Amount         44303 non-null   float64
 16  Payment_Mode         80089 non-null   str
 17  Order_Status         100000 non-null  str
 18  Cancellation_Reason  9031 non-null    str
 19  Delivery_Partner_ID  100000 non-null  str
 20  Delivery_Rating      83477 non-null   float64
 21  Restaurant_Rating    100000 non-null  float64
 22  Order_Day            100000 non-null  str
 23  Peak_Hour            67038 non-null   object
 24  Profit_Margin        100000 non-null  float64
dtypes: float64(9), object(1), str(15)
memory usage: 19.1+ MB

In [16]:
# Find the numerical summary
df.describe()

,Customer_Age,Delivery_Time_Min,Distance_km,Order_Value,Discount_Applied,Final_Amount,Delivery_Rating,Restaurant_Rating,Profit_Margin
count,49907.000000,66641.000000,66530.000000,66673.000000,83285.000000,44303.000000,83477.000000,100000.000000,100000.000000
mean,38.976516,127.475923,16.449242,2081.830126,93.936243,1961.101190,2.991531,4.249680,0.150362
std,12.372157,90.805839,12.256742,1553.628891,108.209904,1557.354417,1.414108,0.722554,0.201888
min,18.000000,20.000000,1.000000,150.000000,0.000000,-150.000000,1.000000,3.000000,-0.200000
25%,28.000000,45.000000,5.470000,673.000000,20.000000,559.000000,2.000000,3.600000,-0.020000
50%,39.000000,120.000000,9.970000,1197.000000,50.000000,1156.000000,3.000000,4.200000,0.150000
75%,50.000000,210.000000,27.430000,3494.000000,100.000000,3375.000000,4.000000,4.900000,0.320000
max,60.000000,300.000000,40.000000,5000.000000,300.000000,4980.000000,5.000000,5.500000,0.500000

# Step 3: Data Cleaning & Preprocessing

In [4]:
# Creating a copy before performing a analysis
df_clean = df.copy()

df_clean.shape

(100000, 25)

3.1 Handling missing values using mean, median, or mode

In [18]:
# check missing values in each column
missing_values = df_clean.isnull().sum()
print(missing_values)

Order_ID                   0
Customer_ID                0
Customer_Age           50093
Customer_Gender        24856
City                   16726
Area                   16685
Restaurant_ID              0
Restaurant_Name            0
Cuisine_Type           16885
Order_Date              1014
Order_Time              1998
Delivery_Time_Min      33359
Distance_km            33470
Order_Value            33327
Discount_Applied       16715
Final_Amount           55697
Payment_Mode           19911
Order_Status               0
Cancellation_Reason    90969
Delivery_Partner_ID        0
Delivery_Rating        16523
Restaurant_Rating          0
Order_Day                  0
Peak_Hour              32962
Profit_Margin              0
dtype: int64

In [19]:
# Display only columns containing missing values
missing_values = missing_values[missing_values > 0]

print("Missing values in each column:")
print(missing_values.sort_values(ascending=False))

Missing values in each column:
Cancellation_Reason    90969
Final_Amount           55697
Customer_Age           50093
Distance_km            33470
Delivery_Time_Min      33359
Order_Value            33327
Peak_Hour              32962
Customer_Gender        24856
Payment_Mode           19911
Cuisine_Type           16885
City                   16726
Discount_Applied       16715
Area                   16685
Delivery_Rating        16523
Order_Time              1998
Order_Date              1014
dtype: int64

In [20]:
# Calculate the percentage of missing values
missing_percentage = (df_clean.isnull().sum() / len(df_clean) * 100).round(2)

print("\nMissing value percentage:")
print(missing_percentage[missing_percentage > 0].sort_values(ascending=False))

Missing value percentage:
Cancellation_Reason    90.97
Final_Amount           55.70
Customer_Age           50.09
Distance_km            33.47
Delivery_Time_Min      33.36
Order_Value            33.33
Peak_Hour              32.96
Customer_Gender        24.86
Payment_Mode           19.91
Cuisine_Type           16.89
City                   16.73
Discount_Applied       16.72
Area                   16.68
Delivery_Rating        16.52
Order_Time              2.00
Order_Date              1.01
dtype: float64

In [21]:
# Check missing values in Financial missing-value summary

financial_cols = [
    "Order_Value",
    "Discount_Applied",
    "Final_Amount"
]

print("Missing financial values:")
print(df_clean[financial_cols].isnull().sum())

print("\nRows with all three financial values missing:")
print(df_clean[financial_cols].isnull().all(axis=1).sum())

Missing financial values:
Order_Value         33327
Discount_Applied    16715
Final_Amount        55697
dtype: int64

Rows with all three financial values missing:
5556

In [22]:
 #Group remaining missing values

numeric_missing = df_clean.select_dtypes(include="number").isnull().sum()

categorical_missing = df_clean.select_dtypes(include=["object", "string", "bool"]
).isnull().sum()

print("Missing numeric values:")
print(numeric_missing[numeric_missing > 0])

print("\n Missing categorical values:")
print(categorical_missing[categorical_missing > 0])

Missing numeric values:
Customer_Age         50093
Delivery_Time_Min    33359
Distance_km          33470
Order_Value          33327
Discount_Applied     16715
Final_Amount         55697
Delivery_Rating      16523
dtype: int64

 Missing categorical values:
Customer_Gender        24856
City                   16726
Area                   16685
Cuisine_Type           16885
Order_Date              1014
Order_Time              1998
Payment_Mode           19911
Cancellation_Reason    90969
Peak_Hour              32962
dtype: int64

First check the categorical values using mode

Check the cancellation reason --> 90969

In [23]:

# Check cancellation reasons by order status

print("Order status distribution:")
print(df_clean["Order_Status"].value_counts())

print("\n Cancellation reason availability by order status:")
print(df_clean.groupby("Order_Status")["Cancellation_Reason"]
    .apply(lambda x: x.isnull().value_counts()))

Order status distribution:
Order_Status
Delivered    84964
Cancelled    15036
Name: count, dtype: int64

 Cancellation reason availability by order status:
Order_Status
Cancelled     False     9031
              True      6005
Delivered     True     84964
Name: Cancellation_Reason, dtype: int64

Handle missing cancellation reasons

For delivered orders, we can label the missing reason as "Not Applicable". For cancelled orders with missing reasons, we should use "Unknown".

In [24]:

# Handle missing cancellation reasons based on order status

delivered_mask = df_clean["Order_Status"] == "Delivered"
cancelled_mask = df_clean["Order_Status"] == "Cancelled"

# Missing reason for delivered orders: not applicable
df_clean.loc[ delivered_mask & df_clean["Cancellation_Reason"].isna(),
    "Cancellation_Reason"] = "Not Applicable"

# Missing reason for cancelled orders: unknown
df_clean.loc[cancelled_mask & df_clean["Cancellation_Reason"].isna(),
    "Cancellation_Reason"] = "Unknown"

# Verify
print("Remaining missing cancellation reasons:",
      df_clean["Cancellation_Reason"].isnull().sum())

print("\nCancellation reason distribution:")
print(df_clean["Cancellation_Reason"].value_counts())

Remaining missing cancellation reasons: 0

Cancellation reason distribution:
Cancellation_Reason
Not Applicable        84964
Unknown                6005
Late Delivery          3059
Customer Cancelled     2993
Restaurant Issue       2979
Name: count, dtype: int64

Check missing values in financial, categorical, rating, and time-related columns. Let's handle the next group: Payment_Mode.

In [25]:

# Check remaining categorical missing values

categorical_cols = [
    "Customer_Gender",
    "Payment_Mode",
    "City",
    "Area",
    "Cuisine_Type"
]

print(df_clean[categorical_cols].isnull().sum())

Customer_Gender    24856
Payment_Mode       19911
City               16726
Area               16685
Cuisine_Type       16885
dtype: int64

Filling unknown for missing categorical value

In [26]:

# Fill missing categorical values with "Unknown"

categorical_cols = [
    "Customer_Gender",
    "Payment_Mode",
    "City",
    "Area",
    "Cuisine_Type"
]

for col in categorical_cols:
    df_clean[col] = df_clean[col].fillna("Unknown")

# Verify
print("Remaining missing categorical values:")
print(df_clean[categorical_cols].isnull().sum())

Remaining missing categorical values:
Customer_Gender    0
Payment_Mode       0
City               0
Area               0
Cuisine_Type       0
dtype: int64

Check missing values in numerical columns

In [27]:
missing_values = df_clean.isnull().sum()

print(missing_values[missing_values > 0].sort_values(ascending=False))

Final_Amount         55697
Customer_Age         50093
Distance_km          33470
Delivery_Time_Min    33359
Order_Value          33327
Peak_Hour            32962
Discount_Applied     16715
Delivery_Rating      16523
Order_Time            1998
Order_Date            1014
dtype: int64

In [28]:
print("Shape:", df_clean.shape)

print(df_clean[
    ["Customer_Age", "Distance_km", "Delivery_Time_Min", "Final_Amount"]
].isnull().sum())

Shape: (100000, 25)
Customer_Age         50093
Distance_km          33470
Delivery_Time_Min    33359
Final_Amount         55697
dtype: int64

Handling missing numerical columns using median

In [29]:
# Fill missing values using the median
median_cols = [
    "Customer_Age",
    "Distance_km",
    "Delivery_Time_Min"
]

for col in median_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

# Verify
print(df_clean[median_cols].isnull().sum())

Customer_Age         0
Distance_km          0
Delivery_Time_Min    0
dtype: int64

Verifying the remining missing values

In [30]:
missing_values = df_clean.isnull().sum()
print(missing_values[missing_values > 0].sort_values(ascending=False))

Final_Amount        55697
Order_Value         33327
Peak_Hour           32962
Discount_Applied    16715
Delivery_Rating     16523
Order_Time           1998
Order_Date           1014
dtype: int64

Checking the missing discounts

Discount_Applied  -->  16715

In [5]:
# Check discount distribution
print(df_clean["Discount_Applied"].value_counts(dropna=False).sort_index())

# Check missing discounts by order status
print(pd.crosstab(
    df_clean["Order_Status"],
    df_clean["Discount_Applied"].isna(),
    margins=True
))

Discount_Applied
0.0      16650
20.0     16569
50.0     16690
100.0    16776
300.0    16600
NaN      16715
Name: count, dtype: int64
Discount_Applied  False   True     All
Order_Status
Cancelled         12450   2586   15036
Delivered         70835  14129   84964
All               83285  16715  100000

Checking Discount_applied with Order_value

In [6]:
# Check whether missing discounts also have missing order values
print(pd.crosstab(
    df_clean["Discount_Applied"].isna(),
    df_clean["Order_Value"].isna(),
    margins=True
))

Order_Value       False   True     All
Discount_Applied
False             55514  27771   83285
True              11159   5556   16715
All               66673  33327  100000

3.2 Removing or Capping Outliers (delivery time, order value)

Detect potential outliers

In [7]:
outlier_cols = ["Delivery_Time_Min", "Order_Value"]

for col in outlier_cols:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df_clean[
        (df_clean[col] < lower) |
        (df_clean[col] > upper)
    ]

    print(f"\nColumn: {col}")
    print("Lower bound:", lower)
    print("Upper bound:", upper)
    print("Number of outliers:", len(outliers))

Column: Delivery_Time_Min
Lower bound: -202.5
Upper bound: 457.5
Number of outliers: 0

Column: Order_Value
Lower bound: -3558.5
Upper bound: 7725.5
Number of outliers: 0

In [8]:
# Check the actual minimum and maximum

for col in ["Delivery_Time_Min", "Order_Value"]:
    print(f"\n{col}")
    print("Minimum:", df_clean[col].min())
    print("Maximum:", df_clean[col].max())
    print("Negative values:", (df_clean[col] < 0).sum())

Delivery_Time_Min
Minimum: 20.0
Maximum: 300.0
Negative values: 0

Order_Value
Minimum: 150.0
Maximum: 5000.0
Negative values: 0

In [ ]:
# Correct Invalid Values So check the values of Profit_Margin

print("Minimum Profit_Margin:", df_clean["Profit_Margin"].min())
print("Negative profit margins:", (df_clean["Profit_Margin"] < 0).sum())

Minimum Profit_Margin: -0.2
Negative profit margins: 27733

Check negative profit margins

In [10]:
# Check profit margin distribution
print(df_clean["Profit_Margin"].describe())

# Count negative, zero, and positive margins
print("\nMargin categories:")
print(pd.Series({
    "Negative": (df_clean["Profit_Margin"] < 0).sum(),
    "Zero": (df_clean["Profit_Margin"] == 0).sum(),
    "Positive": (df_clean["Profit_Margin"] > 0).sum()
}))

# Inspect sample rows with negative margins
print(df_clean.loc[
    df_clean["Profit_Margin"] < 0,
    ["Order_Value", "Discount_Applied", "Final_Amount", "Profit_Margin"]
].head(10))

count    100000.000000
mean          0.150362
std           0.201888
min          -0.200000
25%          -0.020000
50%           0.150000
75%           0.320000
max           0.500000
Name: Profit_Margin, dtype: float64

Margin categories:
Negative    27733
Zero         1506
Positive    70761
dtype: int64
    Order_Value  Discount_Applied  Final_Amount  Profit_Margin
14       4017.0             300.0        3717.0          -0.01
17          NaN              20.0           NaN          -0.09
18          NaN               0.0           NaN          -0.16
20        355.0             100.0         255.0          -0.11
25        483.0              20.0         463.0          -0.01
27          NaN             100.0           NaN          -0.05
29       2553.0              50.0        2503.0          -0.07
35        999.0             100.0         899.0          -0.16
39          NaN              20.0           NaN          -0.18
49          NaN               0.0           NaN          -0.05

3.3 Correcting invalid values (ratings > 5, negative profit margin)

In [11]:
print("Restaurant ratings below 1:",
      (df_clean["Restaurant_Rating"] < 1).sum())

print("Restaurant ratings above 5:",
      (df_clean["Restaurant_Rating"] > 5).sum())

Restaurant ratings below 1: 0
Restaurant ratings above 5: 18019

Correcting restaurant ratings

In [12]:
# Cap restaurant ratings at the maximum allowed value of 5
df_clean["Restaurant_Rating"] = (
    df_clean["Restaurant_Rating"].clip(upper=5)
)

# Verify the correction
print("Ratings below 1:",
      (df_clean["Restaurant_Rating"] < 1).sum())

print("Ratings above 5:",
      (df_clean["Restaurant_Rating"] > 5).sum())

Ratings below 1: 0
Ratings above 5: 0

3.4 Standardizing categorical values

In [13]:
categorical_cols = [
    "Customer_Gender",
    "City",
    "Area",
    "Cuisine_Type",
    "Payment_Mode",
    "Order_Status",
    "Cancellation_Reason"
]

for col in categorical_cols:
    print(f"\n{col}:")
    print(df_clean[col].dropna().unique())

Customer_Gender:
<StringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str

City:
<StringArray>
['Chennai', 'Delhi', 'Mumbai', 'Bangalore', 'Hyderabad']
Length: 5, dtype: str

Area:
<StringArray>
['Central', 'North', 'South', 'East', 'West']
Length: 5, dtype: str

Cuisine_Type:
<StringArray>
['Chinese', 'Arabian', 'Mexican', 'Italian', 'Indian']
Length: 5, dtype: str

Payment_Mode:
<StringArray>
['UPI', 'COD', 'Wallet', 'Card']
Length: 4, dtype: str

Order_Status:
<StringArray>
['Delivered', 'Cancelled']
Length: 2, dtype: str

Cancellation_Reason:
<StringArray>
['Late Delivery', 'Restaurant Issue', 'Customer Cancelled']
Length: 3, dtype: str

3.5 Ensuring logical consistency (e.g., cancelled orders vs ratings)

In [14]:
# Check delivery ratings by order status
print(pd.crosstab(
    df_clean["Order_Status"],
    df_clean["Delivery_Rating"].notna(),
    margins=True
))

Delivery_Rating  False   True     All
Order_Status
Cancelled         2475  12561   15036
Delivered        14048  70916   84964
All              16523  83477  100000

Check cancellation reasons

In [15]:
print(pd.crosstab(
    df_clean["Order_Status"],
    df_clean["Cancellation_Reason"],
    margins=True
))

Cancellation_Reason  Customer Cancelled  Late Delivery  Restaurant Issue   All
Order_Status
Cancelled                          2993           3059              2979  9031
All                                2993           3059              2979  9031

Check whether cancelled orders have a Delivery_Time_Min

In [16]:
print(pd.crosstab(
    df_clean["Order_Status"],
    df_clean["Delivery_Time_Min"].notna(),
    margins=True
))

Delivery_Time_Min  False   True     All
Order_Status
Cancelled           5030  10006   15036
Delivered          28329  56635   84964
All                33359  66641  100000

Converting the CSV file after cleaning and Save locally for backup

In [17]:
df_clean.to_csv("online_food_delivery_cleaned.csv", index=False)

In [18]:
display(df_clean.head(10))

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,NaN,Central,RES936,Restaurant_29,Chinese,10/20/2024,...,NaN,UPI,Delivered,NaN,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,NaN,Female,Chennai,North,RES689,Restaurant_419,Chinese,8/12/2024,...,4849.0,COD,Delivered,NaN,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,NaN,Male,Delhi,NaN,RES723,Restaurant_244,Arabian,12/8/2024,...,737.0,Wallet,Delivered,NaN,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,NaN,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,10/8/2024,...,NaN,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,NaN,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,2/4/2024,...,352.0,Card,Delivered,NaN,DP728,2.0,4.4,Weekend,False,0.12
5,ORD000006,CUST3161,37.0,Other,Chennai,East,RES810,Restaurant_153,Mexican,7/9/2024,...,NaN,Card,Delivered,NaN,DP119,3.0,4.6,Weekday,True,0.24
6,ORD000007,CUST2307,40.0,Other,Delhi,NaN,RES333,Restaurant_302,Chinese,2/14/2024,...,NaN,UPI,Delivered,NaN,DP624,2.0,4.5,Weekday,NaN,0.02
7,ORD000008,CUST5865,NaN,Male,NaN,North,RES696,Restaurant_41,Chinese,5/26/2024,...,3486.0,UPI,Delivered,NaN,DP316,5.0,3.8,Weekend,NaN,0.18
8,ORD000009,CUST4356,NaN,Other,Delhi,Central,RES780,Restaurant_155,Italian,9/7/2024,...,425.0,NaN,Delivered,NaN,DP531,2.0,3.7,Weekend,True,0.08
9,ORD000010,CUST2404,NaN,Female,NaN,South,RES155,Restaurant_368,Chinese,1/22/2024,...,4641.0,NaN,Delivered,NaN,DP338,4.0,4.5,Weekday,True,0.03

In [19]:
print("Current DataFrame missing values:")
print(df_clean.isnull().sum()[df_clean.isnull().sum() > 0])

Current DataFrame missing values:
Customer_Age           50093
Customer_Gender        24856
City                   16726
Area                   16685
Cuisine_Type           16885
Order_Date              1014
Order_Time              1998
Delivery_Time_Min      33359
Distance_km            33470
Order_Value            33327
Discount_Applied       16715
Final_Amount           55697
Payment_Mode           19911
Cancellation_Reason    90969
Delivery_Rating        16523
Peak_Hour              32962
dtype: int64